name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run Tests
      run: echo "Skipping tests in this demo"

    - name: Log into DockerHub
      uses: docker/login-action@v2
      with:
        username: paraajwalweebe
        password: dckr_pat_WhhKKYjE0bW0yxLpLWUGGz3feag

    - name: Build Docker image
      run: docker build -t paraajwalweebe/nodejs-app:latest .

    - name: Push Docker image
      run: docker push paraajwalweebe/nodejs-app:latest

